#![forbid(unsafe_code)]
#![warn(
    clippy::all,
    clippy::char_lit_as_u8,
    clippy::perf,
    clippy::exit,
    clippy::dbg_macro,
    clippy::checked_conversions,
    clippy::dbg_macro,
    clippy::debug_assert_with_mut_call,
    clippy::doc_markdown,
    clippy::empty_enum,
    clippy::enum_glob_use,
    clippy::exit,
    clippy::expl_impl_clone_on_copy,
    clippy::explicit_deref_methods,
    clippy::explicit_into_iter_loop,
    clippy::filter_map_next,
    clippy::filetype_is_file,
    clippy::flat_map_option,
    clippy::equatable_if_let,
    clippy::float_cmp_const,
    clippy::from_iter_instead_of_collect,
    clippy::fallible_impl_from,
    clippy::if_let_mutex,
    clippy::implicit_clone,
    clippy::imprecise_flops,
    clippy::inefficient_to_string,
    clippy::invalid_upcast_comparisons,
    clippy::large_digit_groups,
    clippy::large_stack_arrays,
    clippy::large_types_passed_by_value,
    clippy::let_unit_value,
    clippy::lossy_float_literal,
    clippy::macro_use_imports,
    clippy::manual_ok_or,
    clippy::map_err_ignore,
    clippy::map_flatten,
    clippy::map_unwrap_or,
    clippy::match_on_vec_items,
    clippy::match_same_arms,
    clippy::match_wild_err_arm,
    clippy::match_wildcard_for_single_variants,
    clippy::mem_forget,
    clippy::mismatched_target_os,
    clippy::missing_enforced_import_renames,
    clippy::mut_mut,
    clippy::mutex_integer,
    clippy::manual_let_else,
    clippy::manual_string_new,
    clippy::manual_ok_or,
    clippy::needless_borrow,
    clippy::mem_forget,
    clippy::needless_continue,
    clippy::needless_collect,
    clippy::option_if_let_else,
    clippy::ref_option_ref,
    clippy::needless_for_each,
    clippy::option_option,
    clippy::path_buf_push_overwrite,
    clippy::ptr_as_ptr,
    clippy::rc_mutex,
    clippy::rest_pat_in_fully_bound_structs,
    clippy::unused_self,
    clippy::unreadable_literal,
    clippy::same_functions_in_if_condition,
    clippy::semicolon_if_nothing_returned,
    clippy::single_match_else,
    clippy::string_add_assign,
    clippy::string_add,
    clippy::string_lit_as_bytes,
    clippy::string_to_string,
    clippy::todo,
    clippy::trait_duplication_in_bounds,
    clippy::unimplemented,
    clippy::unnested_or_patterns,
    clippy::useless_transmute,
    clippy::string_add,
    clippy::str_to_string,
    clippy::fn_params_excessive_bools,
    clippy::format_push_string,
    clippy::verbose_file_reads,
    clippy::zero_sized_map_values,
    clippy::as_underscore,
    clippy::linkedlist,
    future_incompatible,
    nonstandard_style
)]

pub mod app;
pub mod config;
pub mod dir;
pub mod dir_experimental;
pub mod external_event;
pub mod ignore;
pub mod marks;
pub mod queue;
pub mod ui;
